### ISSUE TITLE
Whether you will disclose the rest of the code and how long it might take

### ISSUE THREAD

**Issue by xiueran** [samar-khanna/DiffusionSat#3]
Whether you will disclose the rest of the code and how long it might take

**Comment by samar-khanna** [comment]
I will be uploading other portions of the code. As for how long, I can't say at the moment because the process involves transferring over checkpoints and verifying code that was run on a different server, which I no longer have straightforward access to. 

I'm closing this issue to keep just one to track the progress: https://github.com/samar-khanna/DiffusionSat/issues/1
